[versions]
agp = "8.5.0"
android-activity-ktx = "1.9.0"
android-compose = "1.9.0"
coilCompose = "3.0.0-alpha07"
compose-plugin = "1.6.11"
jna = "5.14.0"
observable-viewmodel = "1.0.0-BETA-3"
koinCompose = "1.2.0-Beta4"
kotlin = "2.0.0"
kotlinx-coroutines = "1.8.1"
mavenPublishVanniktech = "0.29.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-compose" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "android-activity-ktx" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
observable-viewmodel = { module = "com.rickclephas.kmp:kmp-observableviewmodel-core", version.ref = "observable-viewmodel" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublishVanniktech = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishVanniktech" }
