name: âš—ï¸ FileKit CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ğŸ’†â€â™€ï¸ Build FileKit
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Check out repository
        uses: actions/checkout@v6

      - name: ğŸ‰ Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: ğŸ”¨ Build project
        run: ./gradlew assemble

  test-desktop:
    name: ğŸ–¥ï¸ Test Desktop
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›ï¸ Check out repository
        uses: actions/checkout@v6

      - name: ğŸ‰ Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: ğŸ§ª Run JVM Tests
        run: ./gradlew jvmTest

  test-android:
    name: ğŸ¤– Test Android
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Check out repository
        uses: actions/checkout@v6

      - name: ğŸ‰ Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: ğŸ§ª Run Android Unit Tests
        run: ./gradlew testAndroidHostTest

  test-ios:
    name: ğŸ Test iOS
    needs: build
    runs-on: macos-latest
    steps:
      - name: ğŸ›ï¸ Check out repository
        uses: actions/checkout@v6

      - name: ğŸ‰ Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: ğŸ§ª Run iOS Tests
        run: ./gradlew iosSimulatorArm64Test

  test-macos:
    name: ğŸ Test macOS
    needs: build
    runs-on: macos-latest
    steps:
      - name: ğŸ›ï¸ Check out repository
        uses: actions/checkout@v6

      - name: ğŸ‰ Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: ğŸ§ª Run macOS Tests
        run: ./gradlew macosArm64Test
